name: JsxposedX 硬核编译流水线

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: # 允许你随时手动点击按钮触发编译

jobs:
  build:
    name: 编译 Android APK
    runs-on: ubuntu-latest

    steps:
    - name: 1. 拉取大牛修改版的源码
      uses: actions/checkout@v4
      with:
        submodules: 'recursive' # 递归拉取可能存在的依赖模块

    - name: 2. 部署 Java JDK 17 环境
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: 3. 部署 Flutter SDK 引擎
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: 4. 获取项目依赖包 (Dart/Flutter)
      run: flutter pub get

    - name: 5. 启动极客混合编译 (Flutter + C++ NDK)
      # 这里使用 debug 模式编译，方便你注入调试，且免去配置安卓签名的繁琐步骤
      run: flutter build apk --debug

    - name: 6. 提取并上传最终产物 (APK)
      uses: actions/upload-artifact@v4
      with:
        name: JsxposedX-Hbp-Modified
        # Flutter 编译后的默认输出路径
        path: build/app/outputs/flutter-apk/app-debug.apk
